### ISSUE TITLE
enhancement: sound effect while alive cabinet is 'eating' things?

### ISSUE THREAD

**Issue by DoomSquirter** [bafomdad/realfilingcabinet#11]
maybe a nomnomnom sound like from openblocks luggage while it ate food items, dunno, could be really silly but is one thing I miss while that bugger is following me around lol

**Comment by bafomdad** [comment]
haha, I don't see why not

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/69f717cfacc007a87c43266d3d9ef400f8f42320
