### ISSUE TITLE
Major Issue - Can't Retrieve Items [1.10.2]-[realfilingcabinet-1.10.2-1.2.61]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [bafomdad/realfilingcabinet#12]
Sneak right click isn't getting the folders.

![2017-01-07_16 18 30](https://cloud.githubusercontent.com/assets/10351221/21745606/44bdeb1e-d4f5-11e6-86ed-7e8d8bd2712e.png)
![2017-01-07_16 18 33](https://cloud.githubusercontent.com/assets/10351221/21745605/44bd9f10-d4f5-11e6-9a3a-d4c0861ceab8.png)
![2017-01-07_16 18 33_2](https://cloud.githubusercontent.com/assets/10351221/21745607/44bed894-d4f5-11e6-9d10-93428c9f5917.png)
![2017-01-07_16 18 34](https://cloud.githubusercontent.com/assets/10351221/21745609/44c72b34-d4f5-11e6-80cd-5323221280f7.png)
![2017-01-07_16 19 12](https://cloud.githubusercontent.com/assets/10351221/21745608/44c69ef8-d4f5-11e6-8d2e-247068296eb5.png)

**Comment by bafomdad** [comment]
This was a new folder extraction behaviour that I introduced somewhere around version 1.2.2 of the mod.

Currently, looking at the N/S/W/E sides of the cabinet will let you extract directly from the slot you're looking at, if a folder exists in that slot, it will show up on your crosshair. Where exactly you look is entirely dependent on the height of the cabinet you're looking at. For just those two folders, you can look towards the bottom.

If you just want the old way of extracting folders, you can look at the top or bottom side, and you'll extract the folder you put in last. I do think this is a little unpolished feature that I've implemented, so I'll find a better way sometime.

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/6712a4662da893d2bfda45bf8dc429a570ba0d6f

**Comment by P3rf3ctXZer0** [comment]
@bafomdad ty
