### ISSUE TITLE
Crafting of Filing Folder with air is possible

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#14]
First, thanks for the mod, I really enjoy it, however I have a few bugs to report. The first one is happening like this:

1. Open the GUI of a (vanilla) crafting table and craft anything (e.g. stone to stone bricks) so that after the craft the grid is completely empty.
2. Without leaving the GUI put an empty filing folder in the crafting grid.

It will now give you a filing folder containing 1 Air. The key seems to be that the grid needs to be empty after a previous craft. You then have to close and re-open the GUI in order for you to be able to craft the next filing folder.

Minecraft: 1.11.2
Forge: 13.20.0.2251
Mods:
  jei_1.11.2-4.2.7.240
  realfilingcabinet-1.11.2-1.2.2

**Comment by bafomdad** [comment]
Definitely reproducible and definitely a bug. Fixed: https://github.com/bafomdad/realfilingcabinet/commit/13197f6a4df4a1118d514c8ab0543616916c81fc

Thanks for the bug report!
