### ISSUE TITLE
Villager from mob folders get randomized and look like farmers

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#15]
Whenever I capture a villager in a mob folder and release him again, the resulting villager is a completely new one. The villager has a different occupation, different trades and always looks like a farmer.

Minecraft: 1.11.2
Forge: 13.20.0.2251
Mods:
  jei_1.11.2-4.2.7.240
  realfilingcabinet-1.11.2-1.2.2

**Comment by bafomdad** [comment]
Hi

By default, the config option for spawning villagers with randomized professions will be set to false, so they will always spawn as a villager with the farmer profession. But their careers and therefore their trades, will still be randomized, as there aren't any good helper methods for making careers the same every time.

Maybe as a possible solution, if you do not wish players to have villagers with randomized trades, is to blacklist them from being picked up by the Mob Folders.

This will be in a todo list, to investigate setting all spawned villagers the same profession, with the same trades.

**Comment by tommyTT** [comment]
Ah, I completely missed that setting in the config file. I thought the mob folders worked like a golden lasso from Extra Utilities just with endless storage. I think I will disable the whole mob storage for the moment, until I have a better idea on how to integrate it into my modpack.

Thanks for your help!

**Comment by bafomdad** [comment]
No problem

The mob folder works because it doesn't store any extra NBT data or information about mobs, like what golden lassos or soul vials do. So you could conceivably capture a nearly dead mob and spawn it back in the world at full health. It's quite silly, really, which is why the recipes for upgrade modules can all be disabled or modified with craft tweaker
