### ISSUE TITLE
Weird entity registry name for the living filing cabinet

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#18]
**Issue Description:**
The registry name for the living filing cabinet is very weird and cause problems for other mods.

**What happens:**
While developing my modpack I started to configure the mobs and needed a overview of the registered entities and their registry names, so I could blacklist them in other mods (e.g. Woot, EvilCraft). I made a registry dump for the entity registry and found that the Filing Cabinet with the living upgrade is registered as "realfilingcabinet:textures/entity/cabinettexture.png". 

**What you expected to happen:**
Something easier and more readable like "realfilingcabinet:cabinet", similar to the normal minecraft registry names. Other mods might have trouble with with things like a "/" and "." in registry names.

**Steps to reproduce:**
I'm using the [TellMe](https://minecraft.curseforge.com/projects/tellme?gameCategorySlug=mc-mods&projectID=225781) Mod to dump all registered entities via the command
`/tellme dump entities`

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
   jei_1.11.2-4.2.10.248
  realfilingcabinet-1.11.2-1.2.21
  tellme-1.11.2-0.5.1

**Your most recent log file where the issue was present:**
https://paste.ee/p/s1eTz (log)
https://paste.ee/p/sAtnf (TellMe entity registry dump)

**Further notes:**
In [RFCEntities.init()](https://github.com/bafomdad/realfilingcabinet/blob/1.11/com/bafomdad/realfilingcabinet/init/RFCEntities.java#L19) the [ResourceUpgradeHelper.MOB_DEFAULT](https://github.com/bafomdad/realfilingcabinet/blob/1.11/com/bafomdad/realfilingcabinet/helpers/ResourceUpgradeHelper.java#L20) resource location is used, but that seems to be for a texture, therefore the weird registry name.

**Comment by bafomdad** [comment]
Heh, yeah, that would bother me too if I came across it myself. I'll have a look at fixing that

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/3e88128fdca0aa5df2932d4f073262f737f4ff8c
