### ISSUE TITLE
[Suggestion] Config option to disable auto pickup of items

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#19]
While developing and testing my personal modpack I came across a balancing problem with the item folders and was wondering if a config option could be added that let's me correct that:
The problem I had was that the first thing I did was find sugar cane (or rice from Actually Additions) and started making a lot of empty folders for all the materials I would collect while mining (cobblestone, dirt, gravel, ...). Since the folders auto pickup the items and have virtually no limit on the amount of items stored, I never had to worry about inventory management while mining. Other mods have items that do similar things (Void Tear from Reliquary, Black Hole Talisman from Botania) but these are only available in the later game. 
My current solution is to gate the crafting of the folders behind one of those items (the void tear), but there are still the mystery folders that will give you the folders and I don't want to remove those. It would be very nice if I could disable the auto pickup feature of the folders for the entire pack. Since I also made the recipe for the filing cabinet more expensive (requires emerald upgrades from Storage Drawers) this would give me the gameplay experience I want to achieve.

**Comment by bafomdad** [comment]
Sure, that could easily be done :] putting this down as a feature request

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/8c2218ad1e067c88d036fc4961a145c11caf9518
