### ISSUE TITLE
ender cabinet crash when using moving drawer

### ISSUE THREAD

**Issue by ehwuts** [bafomdad/realfilingcabinet#2]
crash log: http://pastebin.com/raw/qxUnynnU
steps to reproduce:
place cabinet
put something (like dirt in folder
put folder in cabinet
apply ender upgrade to cabinet
rclick and shift+rclick a few times

**Comment by bafomdad** [comment]
cannot reproduce with build. 

reasoning:
- the .jar file released elsewhere is older
- the mod version in this repo has not been incremented to tell people it is newer

solution:
- commit a change to increment mod version by 1

**Comment by ehwuts** [comment]
could not reproduce with fresh pack and redownload of latest release

**Comment by bafomdad** [comment]
aight, let's close it until it comes up again
