### ISSUE TITLE
Server crash with ClassNotFoundException due to usage of client side code

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#20]
**Issue Description:**
The newest update to RFC doesn't work on servers when Botania integration is enabled.

**What happens:**
A server with both RFC and Botania installed as well as Botania integration enabled for RFC crashes because of initializations that use client side only code.

**What you expected to happen:**
Server shouldn't initialize anything that is not needed.

**Steps to reproduce:**
Start a server world with both Botania and RFC installed and the Botania integration enabled.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
  RFC 1.2.4
  JEI 4.2.10.248
  Baubles 1.4.3
  Botania r1.9-342

**Your most recent log file where the issue was present:**
https://paste.ee/p/RYzcT

**Comment by bafomdad** [comment]
dang it, I do this all the time. This is what I get for not having a test server instance for 1.11.2

Fixed in the next version. I apologise for any inconvenience from this

**Comment by tommyTT** [comment]
No worries, I'm happy to help. I recently experienced these problems myself and I think this way too easy to screw up. This is why I have a stagging area before putting anything on my server. Thanks for your efforts.
