### ISSUE TITLE
Creative instead of Ender Upgrade

### ISSUE THREAD

**Issue by 4Magma** [bafomdad/realfilingcabinet#22]
Tried to use ender upgrade without success. 
As i extract the upgrade with a magnifying glass i got a creative upgrade instead of the ender upgrade.

And how do i use the ender upgrade.
- empty cabinet with upgrade won't take any folders
- cabinet with 8 folders won't take the upgrade
Do i need other type of folders? Tried with several normal one (eg. wood)

**Comment by bafomdad** [comment]
Hi,

What version of minecraft and what version of the mod are you having this trouble with? I am unable to reproduce this on the latest version for either 1.10.2 or 1.11.2

The ender upgrade ideally should be used on a cabinet with at least one normal folder in it. As an ender upgrade without any folder in it would be useless, I also am unable to reproduce the issue of the creative upgrade popping out instead of the ender upgrade.

**Comment by 4Magma** [comment]
1.11.2 with forge 2264 or 65 (currently 79)
Upgrade bug only occurred once, not much tried to repeat.

play offline own custom pack (current files in mods, should most allready since issue):
achunkloader-1.11.2-1.2.0.jar
Aroma1997Core-1.11.2-1.2.0.0.b81.jar
AromaBackup-1.11-2.1.0.0.b64.jar
AutoRegLib-1.1-4.jar
Baubles-1.11-1.4.3.jar
BBG-6.0.1.jar
BetterBuildersWands-1.11-0.11.1.239+9162f74.jar
BirdsNests1.11.2-1.5.1.jar
Chameleon-1.11-3.0.2.jar
Charset-mc1.11.2-0.4.0-pre10-df93b836a769dd21.jar
ChestTransporter-1.11.2-2.7.4.jar
chiselsandbits-13.10.jar
compatlayer-1.11.2-0.2.5.jar
CookingForBlockheads_1.11.2-5.3.20.jar
CraftingCraft_1.11-5.1.1.jar
CraftingTweaks_1.11.2-7.1.6.jar
CraftTweaker-1.11.2-3.0.24.jar
ElevatorMod-1.11.2-1.3.0.jar
EnderCompass-1.11-1.2.5.2.jar
endertanks-1.11.0-1.5.3.jar
ExtraBitManipulation-1.11.2-3.0.5.jar
extrautils2-1.11.2-1.3.3.jar
FastLeaveDecay-MC1.11-1.2.3.jar
Forgelin-1.4.1.jar
Fuel Canister-1.2 MC 1.11.jar
furnus-1.11.2-1.92.jar
GiacomosFishingNet-1.11.2-1.5.1.jar
GiacomosFoundry-1.11.2-1.3.12.jar
Growable Cells-1.11.2-1.0.0.jar
hammerz-1.11.2-0.1.4.27.jar
Harvest-1.11-1.2.0-12.jar
Hwyla-1.8.12-B25_1.11.jar
InGameInfoXML-1.11-2.8.1.91-universal.jar
InventoryTweaks-1.62-beta-82.jar
jei_1.11.2-4.2.11.251.jar
journeymap-1.11.2-5.4.6.jar
justenoughbuttons-1.11.2-1.4.4.jar
LaserLevel-1.11-2.1.0.16-universal.jar
limelib-1.11.2-1.5.3.jar
literalascension-1.11.2-1.0.1.1.jar
llibrary-1.7.4-1.11.2.jar
LunatriusCore-1.11-1.1.2.39-universal.jar
mcjtylib-1.1x-2.3.11.jar
moreoverlays-1.10-mc1.11.2.jar
Neat 1.4-13.jar
NoMoreRecipeConflict-0.7(1.11).jar
notenoughwands-1.1x-1.5.4.jar
Obsidian Pack+.jar
Quark-r1.2-90.jar
RandomThings-MC1.11.2-3.8.1.jar
realfilingcabinet-1.11.2-1.2.49.jar
recycler-1.4.1-1.11.2.jar
redstonepaste-mc1.11.2-1.7.4.jar
refinedstorage-1.4.2.jar
rftools-1.1x-5.91.jar
rftoolsctrl-1.1x-1.6.6.jar
shetiphiancore-1.11.0-3.4.3.jar
SimpleOreGeneration-3.2.0 mc 1.11.2.jar
SimplyConveyors-2.1.2.jar
Stackie-1.11-1.6.0.45-universal.jar
stacksize-1.11.2-1.0.jar
StorageDrawers-1.11.2-4.2.1.jar
supercraftingframe-1.11-1.2.1.89.jar
theoneprobe-1.1x-1.4.5.jar
tinyprogressions-1.11.2-2.2.0-Hotfix.jar
TombManyGraves-1.11.2-3.0.5.jar
ToolBelt-1.11.2-1.4.0.jar
topaddons-1.11.2-0.9.2.jar
torojimaBuildHelper-0.4.2.jar
VeinMiner-1.11-0.35.3.605+dad98e1.jar
WailaHarvestability-mc1.11-1.1.9.jar
xnet-1.1.4.jar
zz-backpacks 1.11.2 - 3.1.8.jar

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/7f96290e7b2c018d537fb9ccd6908a7c428ad2bb
