### ISSUE TITLE
NPE Crash when using the white out tape

### ISSUE THREAD

**Issue by tommyTT** [bafomdad/realfilingcabinet#24]
**Issue Description:**
The game crashes when I try to use the white out tape on a folder in the crafting grid.

**What happens:**
The entire game crashes with a NPE when trying to take out the empty folder from the result slot of the crafting table. After returning to the game both the white out tape and the folder are gone.

**What you expected to happen:**
Taking out the crafting result gives me the empty folder and the white out tape takes durability.

**Steps to reproduce:**
1. Use a mysterious folder and remove the items in it, so there is a valid folder.
2. Get the white out tape and put it in a crafting grid (inventory, normal crafting table).
3. Take out the empty folder from the crafting result slot.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
 jei_1.11.2-4.2.10.248
realfilingcabinet-1.11.2-1.2.49

**If a (crash)log is relevant for this issue, link it here:**
https://paste.ee/p/NIkQK

**Comment by bafomdad** [comment]
Hm, I have already discovered and fixed this NPE crash on my local repo. I will be releasing a new version soon with this fix being a part of it, among other things.

Thanks for the bug report!
