### ISSUE TITLE
Ender Upgrade desync on Server

### ISSUE THREAD

**Issue by Graeter2** [bafomdad/realfilingcabinet#25]
Playing on an All the Mods Expert mode v1.1.1 beta, running Real Filing Cabinet version 1.10.2 1.3.71.

After upgrading a Filing Cabinet with Ender Upgrade (which requires 8 folders to be inside, upgrade will not work with just 1 folder) there is a desync on client side where you obtain a folder that disappears shortly after interacting with it in any way, trying to insert into a cabinet will treat it as an empty hand.

I've also found that if you open and close the drawer it will crash. Unconfirmed if it has to do with Ender Upgrade or Filing Cabinet.

[crash-2017-07-23_14.28.37-client.txt](https://github.com/bafomdad/realfilingcabinet/files/1168573/crash-2017-07-23_14.28.37-client.txt)
[crash-2017-07-23_14.42.35-client.txt](https://github.com/bafomdad/realfilingcabinet/files/1168572/crash-2017-07-23_14.42.35-client.txt)
[crash-2017-07-23_14.49.10-client.txt](https://github.com/bafomdad/realfilingcabinet/files/1168574/crash-2017-07-23_14.49.10-client.txt)

I've attached a few logs from the past hour that may show what is going on with the crash.

I've tested it for this modpack on single player and was able to extract folders that I could take items out of/drop the folder and pick it back up.

Sorry if my report is everywhere, I can make a second ticket for the crash if needed.

**Comment by bafomdad** [comment]
The upgrade part needing a max of 8 folders in it is indeed odd, as are the crash reports. Hopefully they're all related and then I can fix the whole thing in one go.

Thank you for reporting it :]
