### ISSUE TITLE
Mana Folder

### ISSUE THREAD

**Issue by Graeter2** [bafomdad/realfilingcabinet#26]
Botania has items that you have to charge for an extended period of time (Terra Shatterer, Band of Mana, Mana Tablets, etc.) and they do not despawn.

The Mana Folder does despawn after being dropped on a mana pool, is this intended? It does seem to balance a bit and it stops the 'infinite pool' system. Since you'd be generating and storing it at the same rate (doesn't empty/fill instantly) it seems like it shouldn't despawn naturally.

As a side: Maybe if there's a constant supply of mana it won't despawn? I haven't tested.

Maybe add a config option to turn off/on drop despawn timer? (Set it default to never despawn? xP)

**Comment by bafomdad** [comment]
hm, since I did not account for them despawning, I'd say this is very much unintentional. As it is, I don't think there's any need to balance it against itself, when it already can store such a large amount of items in the normal folders in the first place.

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/commit/2deaf604c2d57223768476a16ad42925f04a5eeb
