### ISSUE TITLE
removing items from ender folders via crafting window updates folder incorrectly

### ISSUE THREAD

**Issue by ehwuts** [bafomdad/realfilingcabinet#3]
tested on singleplayer with the 1.7.10-0.3.2 release and forge 10.13.2.1291

with an ender folder containing more than one stack:
- left clicking to remove a stack can be repeated indefinitely without updating folder contents
- shift-clicking correctly updates the contents for all but the last stack removed. e.g. shift clicking a folder containing 208 dirt would, assuming sufficient space give stacks of 64+64+64+16 dirt in inventory while leaving the folder with 16 dirt and behaving as per the second clause of the first bullet below

with an ender folder containing exactly one or less stacks:
- single clicking gives the amount shown without updating folder content, although further attempts to remove that amount again cause brief client desyncs instead of actually giving items
- removing the folder from its crafting window and placing it back in allows removing the just-removed items again, for real
- shift clicking behaves as per single clicking

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/blob/master/com/bafomdad/realfilingcabinet/RealFilingCabinet.java#L42
