### ISSUE TITLE
Issue with Cofh Hammers

### ISSUE THREAD

**Issue by Akitori** [bafomdad/realfilingcabinet#30]
https://github.com/CoFH/Feedback/issues/965

So basically the long and short of it is that my friend used a COFH hammer (iron in this case) to mine a filing cabinet. When it dropped, it lacked any nbt, folders, etc. So, my friend's 3 months of playing on the server and storing were gone due to a simple hammer.

**Comment by bafomdad** [comment]
Thank you for bringing this to my attention. Yes, the way I did it was a little strange, and so I believe it has been fixed now, as of version 1.12.1-0.1.25
