### ISSUE TITLE
Mana filing cabinets aren't accepting mana if folder is totally empty

### ISSUE THREAD

**Issue by Tmtravlr** [bafomdad/realfilingcabinet#31]
**Version**:

Minecraft: 1.12.2
Forge: 14.23.1.2555
This Mod: 1.12.1-0.1.23

**Issue**:

When you take all the mana out of a mana folder, the filing cabinet won't accept mana with it anymore. This is rather annoying, since if the folder totally drains, I have to manually take it out and put some mana in it to get the filing cabinet to work again.

**Steps to Reproduce**:

1. Grab a mana folder and filing cabinet from the creative menu, and place the mana folder in the filing cabinet.
2. Grab a creative mana pool and a spreader from the creative menu. Place down the pool and spreader next to it, pointing into the cabinet.
3. Notice the spreader will not shoot mana into the cabinet.
4. Take the folder out and throw it into the mana pool, setting the pool to put mana into the folder, so it absorbs some.
5. Put it back into the cabinet, and now the mana spreader will work.
6. Take all the mana out of the cabinet, through another mana spreader or sparks, so the folder totally drains
7. Notice you can't put mana into the filing cabinet again.

**Comment by bafomdad** [comment]
Oops. At least this was really simple to fix.
`if (manaSize > 0) return manaSize;` was changed to `if (manaSize >= 0) return manaSize`

Fixed as of version 1.12.1-0.1.25
