### ISSUE TITLE
The file cabinet can't be upgraded with a pick dismantling

### ISSUE THREAD

**Issue by 710590662** [bafomdad/realfilingcabinet#32]
Minecraft 1.12.2
Version 0.12.7.
Dismantling The file cabinet can not be upgraded with a pickaxe, and the new file cabinet is the same.

**Comment by 710590662** [comment]
Version 0.12.7.Dismantling The file cabinet can not be upgraded with a pickaxe, and the new file cabinet is the same.

**Comment by bafomdad** [comment]
should be fixed in version 0.1.29 for 1.12.2
