### ISSUE TITLE
Unable to craft red arrow in realfilingcabinet-1.12.1-0.1.4 

### ISSUE THREAD

**Issue by WonderDog** [bafomdad/realfilingcabinet#34]
I upgraded to realfilingcabinet-1.12.1-0.1.4 and was unable to craft the red arrow.

In has no recipe in JEI and did not work manualy in vanila crafting bench as well as others.

I downgraded to realfilingcabinet-1.12.1-0.1.3 and was able to craft the arrow and it now has a recipe in JEI.

I still had ingredients in a tinkers crafting station from before the downgrade and it was also able to craft the red arrow.

**Comment by bafomdad** [comment]
hah. Okay, that was a typo on my part.

Somewhere between 0.1.3 and 0.1.4 I changed the red arrow recipe to use red dye oredictionary, but wouldn't ya know..typo. It will be fixed and released today. Thanks for the report!
