### ISSUE TITLE
Creative Upgrade Spawned during ATM3 game.  Cannot repeat but would like too. Where is the recipe?

### ISSUE THREAD

**Issue by Spaladino95** [bafomdad/realfilingcabinet#35]
Playing on an All The Mods 3 server where creative upgrades are craftable.  I had a file cabinet with 4 mob folders in them, a witch, a skeleton, a zombie, and a spider.  I put in the life upgrade and mob upgrade then realized I forgot a folder, spiders. When I used my magnifying glass on it to remove the upgrades it gave me just a creative upgrade back.  I lost both a life and mob upgrade but gained a creative upgrade.  I have not been able to repeat the process though no matter how hard I try.  If it is a specific number of mobs per folder to be able to cause it please let me know.  I have now spend days trying to repeat the process and I cannot.

**Comment by bafomdad** [comment]
That is pretty weird!..I am quite certain I do not have any easter eggs in code that pertains to dropping a creative upgrade if certain conditions are met. And since by default, there is no recipe for the creative upgrade (attainable only through the mod's creative tab), this can be labelled a bug. Not repeatable..but a bug nonetheless.

**Comment by Spaladino95** [comment]
Since ATM 3  has creative craftables I was hoping.   Thanks though, I
really do love your mod.  Future thoughts though, some sort of file cabinet
upgrade to hold more folders, having the filter control the folder you
remove when you pull it out, briefcase of some sort that holds 3-6 folders
but still absorbs what ever item is in it.  I use iron backpacks mod to
carry them around  but nothing works when inside the backpack.  Also the
builders wands being able to pull from the folder would be great.  Thanks
for the response.

**Comment by bafomdad** [comment]
I liked the idea of a briefcase so much that I added it as a suitcase item in the newest update :]

**Comment by Spaladino95** [comment]
That's great I look forward to it.
