### ISSUE TITLE
CapabilityProviderFolder does not perform sanity check on actual capability instance

### ISSUE THREAD

**Issue by 3TUSK** [bafomdad/realfilingcabinet#46]
Forwarded from Snownee/Cuisine#16.  
We have received a crash-report that [involves with this chunk of code from our mod, Cuisine][ref-food-container-emptying]:

```java
ItemStack stack = inv.getStackInRowAndColumn(startX, startY);
FoodContainer container = stack.getCapability(CulinaryCapabilities.FOOD_CONTAINER, null);
if (container != null)
{
    CompositeFood food = container.get();
    if (food != null)
    {
        return !container.getEmptyContainer(stack).isEmpty();
    }
}
return false;
```

Notice that the `getCapability` call does not have a accompanied `hasCapability` call. This is clarified and considered as permissible since MinecraftForge/MinecraftForge#4978, which is available since Forge 14.23.4.2733. As such, the `getCapability` in `CapabilityProviderFolder` has [problematic implementation][ref-cap-provider-folder]:

```java
@Nullable
@Override
public <T> T getCapability(@Nonnull Capability<T> capability, @Nullable EnumFacing facing)
{
    return FOLDER_CAP.cast(folder);
}
```

Specifically, it does not check if the `capability` token passed in is indeed the `FOLDER_CAP`. A example crash may be found in the forwarded issue ticket.  
Considering the fact that the recommended Forge version is 14.23.5.2768 as of the time I am writing this, please consider adding a check against the `capability` instance (i.e. `capability == FOLDER_CAP ? FOLDER_CAP.cast(folder) : null`).

[ref-food-container-emptying]: https://github.com/Snownee/Cuisine/blob/40d1bfa9be50f6f7625b63d43b92429896e2c68b/src/main/java/snownee/cuisine/crafting/RecipeFoodEmpty.java#L65-L75
[ref-cap-provider-folder]: https://github.com/bafomdad/realfilingcabinet/blob/a686899252740693e0719df98f5f59bc05adecde/com/bafomdad/realfilingcabinet/items/capabilities/CapabilityProviderFolder.java#L60

**Comment by bafomdad** [comment]
https://github.com/bafomdad/realfilingcabinet/blob/78868f6f50457e26d4f4dd37d6e1f8a53ea95f27/com/bafomdad/realfilingcabinet/items/capabilities/CapabilityProviderFolder.java#L60
