### ISSUE TITLE
Duplicating items with NBT Folders

### ISSUE THREAD

**Issue by jadeonking** [bafomdad/realfilingcabinet#50]
There appears to be a duplication bug when anything with extra data such as NBT and maybe damage or RF (haven't tested all possibilities) Bees in a NBT folder will duplicate when manually inserted and can confirm that Draconic gear can also be duplicated from manual insertion further testing seems to show its an issue surrounding NBT folders

Mod Pack ATM3 Remix B 1.0.0
Mod Version 0.1.73
Minecraft Version 1.12.2

**Comment by jadeonking** [comment]
further inspection shows if you try to quickly put items in it will usually take it after the second insert but if you time your inserts it will never take the original item from you but will duplicate it inside the filing cabinet

**Comment by bafomdad** [comment]
I managed to replicate this issue outside of dev environment, but not in. Curious though, but I guess it is about timing. I'll look at it more and why it only happens with NBT stuff
