### ISSUE TITLE
Ender Folders can't be placed in suitcases?

### ISSUE THREAD

**Issue by Bluberry-Kat** [bafomdad/realfilingcabinet#51]
Using forge version 2772 on 1.12
Mod version: 0.1.77

Expected behavior: Ender Folders can be placed in suitcases and used like regular folders would be expected to.
Actual behavior: Ender Folders are rejected outright.

If this is intended behavior, is it possible to have an ender suitcase that's solely for holding ender folders? I think it'd be a really nice usability bonus.

**Comment by bafomdad** [comment]
it's intended behavior. suitcases are convenient, but not that convenient. and the ender folder does things to ensure it remains in sync much of the time it is in a player's inventory

**Comment by Bluberry-Kat** [comment]
Ah.
I'm a little sad about it, but it makes sense.
