### ISSUE TITLE
[Feature Request] Give suitcases a model when held?

### ISSUE THREAD

**Issue by Bluberry-Kat** [bafomdad/realfilingcabinet#52]
As the title says. 
I think it'd be a cute touch if you could see the player actually hauling around the suitcase, as a 3d model.

Of course, it'd have to be compatible with being in your off-hand, since that's where the suitcase gets the most use.

**Comment by bafomdad** [comment]
this is a good idea, and I really don't see why not :]

it will be added in the next patch after 0.1.77
