### ISSUE TITLE
Mana Mirror is... weird, with Mana Cabinet

### ISSUE THREAD

**Issue by Bluberry-Kat** [bafomdad/realfilingcabinet#53]
![image](https://user-images.githubusercontent.com/20749209/49336732-b9de6880-f5d5-11e8-8b20-6b49137b1556.png)
using version 0.1.77

**Comment by Bluberry-Kat** [comment]
suggested fixes:
either blacklist the mana mirror from the cabinet (sad, but understandable) or change how the mana mirror works some how (probably the more difficult solution)

**Comment by bafomdad** [comment]
looking into how the mana mirror works..it seems that it binds to any instances of IManaPool, which the Mana Cabinet does implement.'

However, the methods that IManaPool implements aren't used by the cabinet in any way, so moving down to IManaReceiver which IManaPool extends seems to fix the issue without any immediate complications.

**Comment by Bluberry-Kat** [comment]
would that interfere with the cabinet's support with sparks?

**Comment by bafomdad** [comment]
it implements ISparkAttachable as a separate interface, so no problems there :]
