### ISSUE TITLE
[Mod Interaction] Forestry Chests Fail To Close

### ISSUE THREAD

**Issue by ScottoMotto** [bafomdad/realfilingcabinet#58]
Forestry chests do not appear to close when Real Filing Cabinet is installed. Affected chests are Apiarist's, Arborist's and Lepidopterist's.
Tested several recent RFC versions. Bug starts at version realfilingcabinet-1.12.1-0.1.75.jar and continues to present. 

Test mod pack for Twitch launcher with minimal mods:
[Real Filing Cabinet Bug-1.0.zip](https://github.com/bafomdad/realfilingcabinet/files/2704707/Real.Filing.Cabinet.Bug-1.0.zip)

**Comment by bafomdad** [comment]
okay, I was able to reproduce this issue when the mod is installed alongside forestry.
investigated a little into what code was added on version 0.1.75 and onwards, leading me to this https://github.com/bafomdad/realfilingcabinet/blob/1.12/com/bafomdad/realfilingcabinet/events/EventHandlerServer.java#L277-L282
which is the container open event that attaches a container listener on opening any container. Unsubscribing this event makes the forestry chests be able to close again. I am not quite sure why it would be forestry related chests..there may be other mods that breaks similarly to this
