### ISSUE TITLE
Dominant-augmented sparks cannot pull from mana cabinets

### ISSUE THREAD

**Issue by codewarrior0** [bafomdad/realfilingcabinet#59]
Certainly related to af513ea18d41707063edc1c4712b1b766ae19d8f since the [EntitySpark makes sure that the tile is an `IManaPool`](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntitySpark.java#L161) before pulling mana from it.

realfilingcabinet-1.12.1-0.1.79.jar

**Comment by bafomdad** [comment]
The change from the IManaPool interface was done to fix a behavior with mana mirrors: https://github.com/bafomdad/realfilingcabinet/issues/53

It is confirmed that dominant augmented sparks cannot pull from mana cabinets, but this issue can be alleviated by putting recessive augmented sparks on the mana cabinets
