### ISSUE TITLE
Placing a file with stuff in it into a crafting station with another file with stuff in it, crashes the game and deletes the second file

### ISSUE THREAD

**Issue by JackRuby1** [bafomdad/realfilingcabinet#62]
Placing a file with stuff in it into a crafting station with another file with stuff in it, crashes the game and deletes the second file that was in your mouse cursor. It doesn't happen with a vanilla crafting table. An empty folder with a filled one doesn't crash, nor does 2 empty ones.
https://pastebin.com/Z5Gm309j

This is still happening in the latest verion you released. realfilingcabinet-1.12.1-0.1.80.jar
A newer crash report, https://pastebin.com/yEm5dymC

Issue from SF4 github: https://github.com/Darkosto/SkyFactory4Issues/issues/172

**Comment by bafomdad** [comment]
For future reference..

It crashed on this line: https://github.com/bafomdad/realfilingcabinet/blob/1.12/com/bafomdad/realfilingcabinet/crafting/FolderMergeRecipe.java#L97

more or less nearly a year ago, tinker's made changes relating to some fastworkbench stuff that broke the recipe a little bit: https://github.com/SlimeKnights/TinkersConstruct/blame/82b05efce96599b778f78fe29e64a858fe0e7ed3/src/main/java/slimeknights/tconstruct/tools/common/inventory/ContainerCraftingStation.java#L178

In versions of tinker's construct built before that change was made, the crash does not happen. Consequently, any filing cabinet mod versions older than 0.1.83 will crash with any tinker's construct versions newer than 2.9.1.65
