### ISSUE TITLE
Feature Request - An auto insert folder

### ISSUE THREAD

**Issue by delta2k** [bafomdad/realfilingcabinet#64]
hey. is it possible to make a new item "auto insert folder" that when placed inside a file cabinet any new items you right click on the cabinet with will be registered with each folder so you dont have to keep combining them in a crafting grid. its more of a quality of life feature.

**Comment by Garonne** [comment]
Actually... That would also solve my enhancement request - [#77] fluid folders for unplacable fluids - if I could just stick an empty fluid folder into a cabinet and pipe some fluid in.
