### ISSUE TITLE
[1.10.2] IllegalArgumentException client crash

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [bafomdad/realfilingcabinet#7]
[fml-client-latest.log.txt](https://github.com/bafomdad/realfilingcabinet/files/593407/fml-client-latest.log.txt)

**Comment by bafomdad** [comment]
Hi, thanks for the bug report!

I have a few questions myself: Does this happen every time, or only sometimes? And what were you doing before the crash, if possible?

**Comment by Rumpelstiltskinny** [comment]
Only attempted to replicate it once. Was using a moving wand on the filing cabinet to relocate the TE.

**Comment by bafomdad** [comment]
Huh, okay. I'll add some more checks to see if it keeps it from happening.

Also I forgot to put the information on the curse page, but you can break the cabinets with pickaxes and they'll keep their contents.

**Comment by Rumpelstiltskinny** [comment]
Keeping contents when broken is an awesome feature, had I known that I would not have attempted to move the cabinet with a wand. Only recently began using your mod because I'm migrating my storage system to AE2 and the Quantum Storage that held my cobblestone was not being read by ME Storage Bus. At least your cabinet provides the single stack output slot for Storage Buses to read, any chance you could expose the entire cabinet contents so that totals appear in AE2 panels?

edit: wrong place to ask the above question. I could open a new Enhancement issue if desired?

**Comment by bafomdad** [comment]
Sure, no problem. I'll tag that issue appropriately :)
