### ISSUE TITLE
AE2 Fluid Storage bus unable to pull fluids from a fluid filing cabinet

### ISSUE THREAD

**Issue by luna-system** [bafomdad/realfilingcabinet#72]
Sky Factory 4, MC 1.12.2, RFC 0.1.84

After a bit of testing I've found that there is an issue with an AE2 network pulling fluids from the filing cabinet. For testing purposes I have a filing cabinet with the fluid upgade and one fluid folder being constantly filled with water. I then connected a Fluid Storage Interface to the filing cabinet and set up an ME Fluid Terminal and powered the network. The Terminal shows an accurate reflection of available fluids. So far so good. However if we attach any tank to the network with a Fluid Export But, and we configure the bus to export that water, nothing is exported.

Now, as a comparison, I set up the exact same build with a ME Drive replacing the fluid filing cabinet and put in a Fluid Cell and pumped water into it. The export bus immediately began exporting water to the tank. As a final test I set up a tank (a Cyclic Fluid Storage Tank, specifically) in place of the ME Drive, attaching it to the network with a Fluid Storage Bus, and again the exporter worked normally.

Unfortunately whatever interaction that is causing this to fail doesn't appear to be logged to the console.

**Comment by luna-system** [comment]
Not sure if related, but at least in SF4 I'm not able to pull fluids from the folder by BC liquiducts or Cyclic cables either. The only way I've found to systematically remove fluids from folders is to have an automatic user "use" the folder on a fluid annihilation plane.

**Comment by Garonne** [comment]
Based on the Wiki you can only import/extract fluids from cabinets if you set a filter above it... So ducts and AE2 should probably only work in that case... Didn't check myself yet.

Just found that bit of info when I was searching for a way to get a folder with non-placable liquids... Aparently not possible yet...
