### ISSUE TITLE
Crash on load 1.12.2 

### ISSUE THREAD

**Issue by Mercurious1** [bafomdad/realfilingcabinet#81]
Using:  realfilingcabinet-1.12-0.2.0.7.jar

Crash Report: https://paste.dimdev.org/alayudikem.mccrash

**Comment by Mercurious1** [comment]
Also, it worked prior to this update

**Comment by ghost** [comment]
Issue is identical to BuildCraft/BuildCraft#4412

**Comment by bafomdad** [comment]
should be fixed in version 0.2.0.9 with https://github.com/bafomdad/realfilingcabinet/commit/557569b3a04ce9d14e55cddcc6ab6319bd557adb

**Comment by Mercurious1** [comment]
Thanks will try soon and let you know that all is good :)
