### ISSUE TITLE
Mana cabinet doesn't accept mana

### ISSUE THREAD

**Issue by Vlambeer1** [bafomdad/realfilingcabinet#82]
Using:  realfilingcabinet-1.12-0.2.0.9.jar

I'm trying to fill a mana cabinet with mana, it is filled with one half-filled mana folder and the rest of the folders is empty. It does not want to accept mana, not from a spreader aimed at it or sparks with augments (tried dominant and recessive)

**Comment by bafomdad** [comment]
thank you for the report. I think I see the solution for this bug already
