### ISSUE TITLE
Storage Networks only showing 1 stack, but not interactiveable with withdrawing/autocrafting

### ISSUE THREAD

**Issue by JackRuby1** [bafomdad/realfilingcabinet#85]
If you connect a storage network up to a filing cabinet, it'll only show 1 stack of each item in the folder, but you cannot pull any of those items out our use an autocrafter like AE2's to craft with them.
realfilingcabinet-1.12-0.2.0.11.jar	
SF4 406

**Comment by BloodyRnar** [comment]
Can confirm.
Using SimpleStorageNetwork-1.12.2-1.7.6.jar
with realfilingcabinet-1.12-0.2.0.11.jar

Simple Storage Master
Storage Request Table
Storage Link Cable
Real Filing Cabinet

Tested with:
A single folder with Oak Wood
Multiple folders with different items (Oak Wood, Sticks)
Auto Folders loaded via a hopper

Partially Working:
With any number of folders and an item frame above the cabinet.
- The item in the item frame works, other items in the cabinet do not (This is an expected result)

The expected result of having multiple folders with different items all being available when connected to a Storage Link Cable.

Can confirm that Simple Storage Networks is working with other 'Chest' containers.
(Chests, Rustic Cabinets and others)
