### ISSUE TITLE
shift+leftclicking the air not working with Fluid folder

### ISSUE THREAD

**Issue by poswar** [bafomdad/realfilingcabinet#86]
Getting lava from pool is now very hard as shift+leftclicking the air is not working with realfilingcabinet-1.12-0.2.0.15 and forge 14.23.5.2836. 

It looks like the code bellow is not beeing called:

`

	@Override
    public boolean onEntitySwing(EntityLivingBase entityLiving, ItemStack stack) {
        
		if (entityLiving instanceof EntityPlayer && entityLiving.isSneaking()) {
			if (!stack.isEmpty() && stack.getItem() == this) {
				if (stack.getItemDamage() == 4) {	
					NBTTagCompound tag = stack.getTagCompound();
					tag.setBoolean(StringLibs.RFC_PLACEMODE, !tag.getBoolean(StringLibs.RFC_PLACEMODE));
					return true;
				}
			}
		}
		return false;
    }
`

**Comment by bafomdad** [comment]
it was left out of the mod in later releases following a rewrite. the reasoning behind this was realizing the onEntitySwing method caused minor issues with the fluid folders considering being inserted/taken out of the filing cabinet being a "swing event" and toggling place modes accordingly.

it has been re-introduced to the mod again, as of version 0.2.0.19. though this time the means of toggling is shift+scroll while holding any of the filled fluid folders.
