### ISSUE TITLE
stops working after a few minuets 

### ISSUE THREAD

**Issue by 5kedone** [bafomdad/realfilingcabinet#9]
realfilingcabinet-1.11-1.0.3.jar on latest forge 

after a few minutes it stops working no amount of right clicking makes draw open or anything work , its a shame because i really like this mod so far, yeah its abit annoying having to take every folder out to get to the one i need but hay its cheap lol

**Comment by bafomdad** [comment]
I've encountered this problem myself before. It "softlocks", for lack of a better term. There's no errors or crashes being logged. 
It seems consistent in that removing or changing whatever was constantly accessing the filing cabinets (like a pipe or things that can access the inventory being attached to it) will fix it again. So while things are accessing it a few too many times, it looks as if the filing cabinet has given up all hope of opening or closing itself.

It's definitely something I'll have to look into.

**Comment by 5kedone** [comment]
Let me know if you need me to test a new verison lol

**Comment by bafomdad** [comment]
Well, a reliable way to reproduce this bug every time when it's needed would be nice, so it could have a better chance of being fixed rather than waiting for it to break.

**Comment by 5kedone** [comment]
Will have a play about today and see what I can do lol, also is there a
plan for it to be easier to get the folder you want out ?
